// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: options.proto

#ifndef PROTOBUF_options_2eproto__INCLUDED
#define PROTOBUF_options_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace Net {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_options_2eproto();
void protobuf_AssignDesc_options_2eproto();
void protobuf_ShutdownFile_options_2eproto();


// ===================================================================


// ===================================================================

static const int kNMsgIDFieldNumber = 54321;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  nMsgID;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace Net

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_options_2eproto__INCLUDED
